### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by lambdafu** [stevengj/subsuper-proposal#5]
It might be worth mentioning physics, too. Close enough to math and programming, and obvious application. In fact, I found this github project because I was going to write my own proposal so I can type the name of elementary particles in Unicode (from the Standard Model, in particular the two other neutrinos \nu_\mu and \nu_\tau as well as the W^\plus and W^\minus boson).  Do you think including physics would water down the proposal?

**Comment by stevengj** [comment]
In previous proposals for super/subscripts in Unicode, the objection was that people should just use HTML or some other formatting language for formatting, and hence there was no need to support this in Unicode.

I want to focus on programming (including computational physics, of course), because in programming languages using an external formatting system (like HTML or a word processor) is not possible.

**Comment by miguelraz** [comment]
Sorry to comment on a closed thread, but was redirected here after a comment by @jiahao on Julia slack.

I think there is a case to put forth with Unicode's impact on programming in computational physics in at least one respect: fully fledged Einstein Notation for tensors.

https://en.wikipedia.org/wiki/Einstein_notation

Infuriatingly, not all greek letters are availabe, which are used to denote 0:3, and latin letters are used to index 1:3. For example, in [this link](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) one can see that the greek letters `delta`, `theta`, `iota` have no subscript counterpart, whilst `rho` has no superscript counterpart. A crucial aspect of using indices in Einstein notation is "lowering" or "raising" them from super/subscripts to the other. 

This proposal could at least homogenize such a capability, if not outright allow one to implement it in general.

In particular, heavy duty relativistic codes have run on legacy languages and have simply given up on usability. I think having super and subscripts available would be a great boon to the development, maintainability and, readability of gravitational codes specifically, and physics code in general as well.

**Comment by stevengj** [comment]
Yes, that falls under programming computational physics.  Einstein notation is one of many, many notations where both greek and latin subscripts and superscripts are used extensively.

**Comment by miguelraz** [comment]
I thought we could use some more (prepared) used cases, hopefully I can keep adding/editing this comment as evidence piles.

Physics:
1. Vectors are indicated by an arrow above, Second rank tensors use a double arrow, higher order tensors use the index notation. [2, p,3] 
2. Neutrinos require the `\mu` and `\tau` subscripts [2, p.12]
3. Nuclear configuration notation require several fractions as subscripts [2, p.14]
4. The equals symbol with a tilde on top means 'corresponds to'
5. The circumflex accent  ( hat vector) can mean maximum, or minimum value, depending on where it points, whilst the squiggle tilde is used for the rms value. [2, p. 51]
6. The universal constants of vacuum permittivity and permeability require a  º symbol as a subscript. [2, p. 54]
7. The Kronecker delta \delta^i_j, Levi-Civita symbol \epsilon_ij
8. Special functions make extensive use of a a specified (n) derivative  as superscript with respect to a parameter (m) usually denoted at the bottom. See Spherical Harmonics and functions with last names [4].

Chemistry
1. \Delta_vap*E_{m,b} is the molar energy of vaporization.   [1, p. 55]
2. \eta_{inh} is the inherent viscosity - SI Unit m^3 kg ^-1
3. Polymerization reactions require the need for the notation `P_x + P_y -> P_{x+y}` [1, p. 72]
4. Units for degree of crystallinity are `w_{c,h}`
5.  Modulated smectic mesophases SmÃ, and SmC with a tilde, which can't be currently drawn. [1, p 112]
6. Anisotropy in general requires the squiggle tilde on top of the quantity being referred to, see [1,p. 114]
7. Stochiometric equations sometimes need to describe a molecule/atom as aqueous, with the "aq" subscript.

Mathematics:
1. Limit, max, min, and `\Sigma`, supremum, infimum,  Unions, Intersections, and Multiplication notation have subscripts to delimit the set under consideration, or process.
2. Derivatives up to order n (and not just 1-9), with the use of a parenthesis.
3. Partial derivatives `can be annotated as \delta_xx`, and second partial derivatives may have a subscripted index number, as well as an exponent of 2.
4. Specifying the neighbourhood of a topological ball - `B_\epsilon`
5. The negative infinity sign is used as a subscript for integrals
6. X with a caret (^) on top  is used as an estimator of state X [3]
7. ...Almost half the notation index of [4] can't be expressed without super/subscripts.
8. The | bar when applied to a domain denotes with superscripts and subscripts the upper and lower bounds of evaluation - amongst many types of set restrictions.
9. In Integral Equations, a degenerate kernel requires a sum over an index j=1<=n with functions \phi_j(x) and \psi*_j(x). [4, p. 556]

---
References.
[1]. [Compendium of Polymer Terminology and Nomenclature IUPAC 2008](https://www.iupac.org/cms/wp-content/uploads/2016/01/Compendium-of-Polymer-Terminology-and-Nomenclature-IUPAC-Recommendations-2008.pdf)
[2]. [Symbols, Units, Nomenclature and Fundamental Constants in Physics, IUPAP  - Commission C2 SUNAMCO 2010 reprint](http://iupap.org/wp-content/uploads/2014/05/A4.pdf)
[3]. Stochastic Differential Equations, Bernt Oksendal, Sixth Edition, Springer.
[5]. Mathematical Physics - A Modern Introduction to its Foundations, Sadri Hassani, 2013.
[4]  A Comprehensive introduction to Differential Geometry, Michael Spivak, Vol.1, p. 478, 3rd edition.

*: I attempted to find notation that would fit for CS, but my Knuth Vol. 1 on AOCP and CSLR couldn't give more examples than the standard maths notation.

As usual, critiques welcome.
